version: '3.5'
services:
  exchange-bot:
    build: ./
    container_name: exchange-bot
    volumes:
      - ./members.txt:/app/members.txt
    restart: always
    environment:
      - TELEGRAM_BOT_TOKEN=